# Files that are used for bulding a dictionary
#
# This file was introduced just to have single locations of file names
# for scripts is bin/group* and Dictionary/Makefile
# --dk
#
INDICT=base.lst base-compound.lst names.lst computer.lst economics.lst dstu_kds.lst geography.lst lang.lst colors.lst science.lst medicine.lst chemistry.lst base-abbr.lst exceptions.lst pronouns.lst hypocoristic.lst slang.lst
SORTED=base.lst base-compound.lst names.lst computer.lst economics.lst geography.lst colors.lst science.lst medicine.lst chemistry.lst base-abbr.lst slang.lst twisters.lst
SPACED=exceptions.lst pronouns.lst dstu_kds.lst lang.lst

NOTSORTED=exceptions.lst pronouns.lst
NOTINDICT=misc.lst
NOTSPACED=base.lst base-compound.lst names.lst computer.lst economics.lst geography.lst science.lst colors.lst medicine.lst chemistry.lst base-abbr.lst hypocoristic.lst slang.lst
